name: e2e

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Setup Kustomize
        uses: ./.github/actions/kustomize
      - name: Run test
        run: make test
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build
        run: sudo go build -o ./bin/kustomizer ./cmd/kustomizer
      - name: Smoke tests
        run: |
          ./bin/kustomizer apply testdata/plain/ --name=test --revision=1.0.0
           kubectl -n kustomizer-demo get svc frontend 2>&1 | grep frontend
          rm -rf testdata/plain/frontend
          ./bin/kustomizer apply testdata/plain/ --name=test --revision=1.1.0
          kubectl -n kustomizer-demo get svc frontend 2>&1 | grep NotFound
          ./bin/kustomizer delete --name=test
      - name: Debug failure
        if: failure()
        run: |
          kubectl version --client --short
          kubectl -n default get configmaps -oyaml
          kubectl -n kustomizer-demo get all
